# Generated by Django 5.0.1 on 2024-01-20 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_column='username', max_length=100, unique=True, verbose_name='User Name')),
                ('address', models.TextField(db_column='address', verbose_name='Address')),
                ('email', models.EmailField(db_column='email', max_length=100, unique=True, verbose_name='Email')),
                ('password', models.CharField(db_column='password', max_length=128, verbose_name='Password')),
                ('number', models.CharField(db_column='number', max_length=20, verbose_name='Number')),
                ('profilePicture', models.ImageField(db_column='profile_picture', max_length=512, upload_to='upload/', verbose_name='Profile Picture')),
                ('is_active', models.BooleanField(db_column='is_active', default=True, verbose_name='Is Active')),
                ('is_staff', models.BooleanField(db_column='is_staff', default=False, verbose_name='Is Staff')),
                ('is_superuser', models.BooleanField(db_column='is_superuser', default=False, verbose_name='Is Superuser')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name_plural': 'user',
                'db_table': 'users',
                'managed': True,
            },
        ),
    ]
