# Generated by Django 5.0.1 on 2024-01-20 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='profilePicture',
            field=models.ImageField(db_column='profile_picture', max_length=512, upload_to='profiles/', verbose_name='Profile Picture'),
        ),
    ]
