# Generated by Django 5.0.1 on 2024-01-20 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='name', max_length=70, verbose_name='Name')),
                ('picture', models.ImageField(db_column='picture', max_length=512, upload_to='products/', verbose_name='Picture')),
                ('price', models.FloatField(db_column='price', verbose_name='Price')),
                ('description', models.TextField(db_column='description', verbose_name='Description')),
            ],
            options={
                'verbose_name_plural': 'product',
                'db_table': 'products',
                'managed': True,
            },
        ),
    ]
